language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install nose coverage Genshi SQLAlchemy Beaker ToscaWidgets Routes repoze.profile
  - pip install -e . --use-mirrors
script: ./setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#webcore"
    on_success: change
    on_failure: change
