language: python
python:
  - "2.6"
  - "2.7"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - pip install . --use-mirrors
script: python setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#webcore"
    on_success: change
    on_failure: change
